Tourfirm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TourfirmApp.urls')),
    path('api/', include('TourfirmApp.api.Shop.urls'))
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TourfirmApp/api/Shop/urls.py
from django.urls import path, include
from .views import (
    CountryListAPIView,
    CountryDetailAPIView,
    OrderCreateAPIView
)



urlpatterns = [
    # path('category/create/', CategoryCreateAPIView.as_view(), name='api_category_create_url'),
    # path('category/', CategoryListAPIView.as_view(), name='api_category_list_url'),
    # path('category/<str:slug>/', CategoryDetailAPIView.as_view(), name='api_category_detail_url'),
    # # path('users/<int:id>/update/', UserUpdateAPIView.as_view(), name='api_user_update_url'),
    # path('category/<str:slug>/delete/', CategoryDeleteAPIView.as_view(), name='api_category_delete_url'),
    # path('token-auth/', views.obtain_auth_token, name='api_token_auth_url')
    # path('product/create/', ProductCreateAPIView.as_view(), name='api_product_create_url'),
    # path('product/<str:slug>/', ProductDetailAPIView.as_view(), name='api_product_detail_url'),
    # path('product/', ProductListAPIView.as_view(), name='api_product_list_url'),
    # path('product/<str:slug>/update/', ProductUpdateAPIView.as_view(), name='api_product_update_url'),
    # path('product/<str:slug>/delete/', ProductDeleteAPIView.as_view(), name='api_product_delete_url'),
    # path('cart-item/create/', CartItemCreateAPIView.as_view(), name='api_cart_item_create_url'),
    path('shop/country/', CountryListAPIView.as_view(), name='api_country_list_url'),
    path('shop/country/<str:slug>/', CountryDetailAPIView.as_view(), name='api_country_detail_url'),
    path('shop/order/create/', OrderCreateAPIView.as_view(), name='api_order_create_url'),
    path('users/', include('TourfirmApp.api.Users.urls'))
]

TourfirmApp/api/Users/urls.py
from django.urls import path
from .views import UserListAPIView, UserDetailAPIView, UserUpdateAPIView, UserDeleteAPIView, UserCreateAPIView
from rest_framework.authtoken import views
urlpatterns = [
    path('create/', UserCreateAPIView.as_view(), name='api_user_create_url'),
    path('', UserListAPIView.as_view(), name='api_user_list_url'),
    path('<int:id>/', UserDetailAPIView.as_view(), name='api_user_detail_url'),
    path('<int:id>/update/', UserUpdateAPIView.as_view(), name='api_user_update_url'),
    path('<int:id>/delete/', UserDeleteAPIView.as_view(), name='api_user_delete_url'),
    path('token-auth/', views.obtain_auth_token, name='api_token_auth_url'),
]

TourfirmApp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
   path('', home, name='home_url'),
   path('country/<str:slug>/', CountryDetail.as_view(), name="country_detail_url"),
   path('tours/', ToursList.as_view(), name="tours_list_url"),
   path('cart/', cart_view, name="cart_url"),
   path('add-to-cart/', add_to_cart_view, name="add_to_cart_url"),
   path('remove-from-cart/', remove_from_cart_view, name="remove_from_cart_url"),
   path('change-item-qty/', change_item_qty, name="change_item_qty_url"),
   path('checkout/', checkout_view, name="checkout_url"),
   path('order/', order_create_view, name="create_order_url"),
]

TourfirmApp/models.py
from django.db import models
from django.shortcuts import reverse
from decimal import Decimal
from django.conf import settings
import requests
import json
# Create your models here.


class Country(models.Model):
   name = models.CharField(max_length=20)
   slug = models.SlugField()
   author = models.CharField(max_length=20)
   description = models.TextField()
   price = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
   main_image = models.ImageField(upload_to='main/')
   background_image = models.ImageField(upload_to='background_images/', blank=True)
   image_1 = models.ImageField(upload_to='images/', blank=True)
   image_2 = models.ImageField(upload_to='images/', blank=True)
   image_3 = models.ImageField(upload_to='images/', blank=True)
   image_4 = models.ImageField(upload_to='images/', blank=True)
   sities = models.CharField(max_length=100)
   better = models.BooleanField(default=False)
   
   def __str__(self):
      return self.name

   def get_absolute_url(self):
      return reverse('country_detail_url', kwargs={'slug': self.slug})


class CartItem(models.Model):
   country = models.ForeignKey(Country, on_delete=models.CASCADE)
   qty = models.PositiveIntegerField(default=1)
   item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

   def __str__(self):
      return "Cart item #{0}".format(self.id)


class Cart(models.Model):
   items = models.ManyToManyField(CartItem, blank=True)
   cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

   def __str__(self):
      return str(self.id)

   def add_to_cart(self, slug):
      cart = self
      country = Country.objects.get(slug=slug)
      new_item, _ = CartItem.objects.get_or_create(country=country, item_total=country.price)
      if new_item not in cart.items.all():
         cart.items.add(new_item)
         cart.save()

   def remove_from_cart(self, slug):
      cart = self
      country = Country.objects.get(slug=slug)
      for cart_item in cart.items.all():
         if cart_item.country == country:
            cart.items.remove(cart_item)
            cart.save()

   def change_qty(self, cart_item, qty):
      cart = self
      cart_item.qty = int(qty)
      cart_item.item_total = int(qty) * Decimal(cart_item.country.price)
      cart_item.save()
      new_cart_total = 0.00
      for item in cart.items.all():
         new_cart_total += float(item.item_total)
      cart.cart_total = new_cart_total
      cart.save()


ORDER_STATUS_CHOICES = {
   ('Принят в обработку', 'Принят в обработку'),
   ('Выполняется', 'Выполняется'),
   ('Оплачен', 'Оплачен')
}


class Order(models.Model):
   items = models.OneToOneField(Cart, on_delete=models.CASCADE, verbose_name='Корзина #')
   total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
   first_name = models.CharField(max_length=150)
   last_name = models.CharField(max_length=150)
   phone = models.CharField(max_length=30)
   address = models.CharField(max_length=255, blank=True)
   buying_type = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')), default="Самовывоз", blank=True)
   date = models.DateTimeField(auto_now_add=True)
   comment = models.TextField(blank=True)
   status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES)

   def __str__(self):
      return "Заказ №{0}".format(str(self.id))

   

TourfirmApp/api/Shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, JsonResponse 
from TourfirmApp.models import (
    Country,
    Order
)


from .serializers import (
    CountryListSerializer,
    CountryDetailSerializer,
    OrderCreateSerializer
)


from .pagination import ProductLimitOffsetPagination, ProductPageNumberPagination



from rest_framework.views import APIView

from rest_framework.generics import (
   ListAPIView, 
   RetrieveAPIView, 
   UpdateAPIView, 
   DestroyAPIView, 
   CreateAPIView,
   RetrieveUpdateAPIView
)

from rest_framework.pagination import (
    LimitOffsetPagination,
    PageNumberPagination
)



class CountryListAPIView(ListAPIView): 
    queryset = Country.objects.all()
    serializer_class = CountryListSerializer

    #def get_queryset()


class CountryDetailAPIView(RetrieveAPIView):
    queryset = Country.objects.all()
    serializer_class = CountryDetailSerializer
    lookup_field = 'slug'


# class UserUpdateAPIView(RetrieveUpdateAPIView):
#     queryset = User.objects.all()
#     serializer_class = UserUpdateSerializer
#     lookup_field = 'id'
   


# class CategoryDeleteAPIView(DestroyAPIView):
#     queryset = Category.objects.all()
#     serializer_class = CategoryDetailSerializer
#     lookup_field = 'slug'


# class CategoryCreateAPIView(CreateAPIView):
#     queryset = Category.objects.all()
#     serializer_class = CategoryCreateSerializer


# class ProductCreateAPIView(CreateAPIView):
#     queryset = Product.objects.all()
#     serializer_class = ProductCreateSerializer

# class ProductDetailAPIView(RetrieveAPIView):
#     queryset = Product.objects.all()
#     serializer_class = ProductDetailSerializer
#     lookup_field = 'slug'
    

# class ProductListAPIView(ListAPIView): 
#     queryset = Product.objects.all()
#     serializer_class = ProductListSerializer
#     pagination_class = ProductPageNumberPagination

#     #def get_queryset()


# class ProductUpdateAPIView(RetrieveUpdateAPIView):
#     queryset = Product.objects.all()
#     serializer_class = ProductUpdateSerializer
#     lookup_field = 'slug'


# class ProductDeleteAPIView(DestroyAPIView):
#     queryset = Product.objects.all()
#     serializer_class = ProductDetailSerializer
#     lookup_field = 'slug'

# class CartItemCreateAPIView(CreateAPIView):
#     queryset = CartItem.objects.all()
#     serializer_class = CartItemCreateSerializer


class OrderCreateAPIView(CreateAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderCreateSerializer

TourfirmApp/api/Users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, JsonResponse 
from django.contrib.auth.models import User


from .serializers import (
    UserListSerializer,    
    UserDetailSerializer,
    UserUpdateSerializer,
    UserCreateSerializer
)
from .permissions import IsOwnerOrReadOnly


from rest_framework.authentication import TokenAuthentication
from rest_framework.views import APIView
from rest_framework.permissions import (
   IsAuthenticated,
)
from rest_framework.generics import (
   ListAPIView, 
   RetrieveAPIView, 
   UpdateAPIView, 
   DestroyAPIView, 
   CreateAPIView,
   RetrieveUpdateAPIView
)

from rest_framework.authentication import TokenAuthentication

class UserListAPIView(ListAPIView): 
    queryset = User.objects.all()
    serializer_class = UserListSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    #def get_queryset()


class UserDetailAPIView(RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserListSerializer
    lookup_field = 'id'


class UserUpdateAPIView(RetrieveUpdateAPIView):
    queryset = User.objects.all()
    serializer_class = UserUpdateSerializer
    lookup_field = 'id'
   


class UserDeleteAPIView(DestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserDetailSerializer
    lookup_field = 'id'


class UserCreateAPIView(CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserCreateSerializer
    

TourfirmApp/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import JsonResponse, HttpResponse
from .models import Country, Cart, CartItem, Order
from django.views.generic import View 
from decimal import Decimal
from .forms import OrderForm
from django.contrib import messages
import requests
import json
import pprint

def home(request):
   countries = Country.objects.filter(better=True)
   return render(request, 'TourfirmApp/index.html', context={'countries':countries})

class CountryDetail(View):
   def get(self, request, slug):
      try: 
         cart_id = request.session['cart_id']
         cart = Cart.objects.get(id=cart_id)
         request.session['total'] = cart.items.count()
      except:
         cart = Cart()
         cart.save()
         cart_id = cart.id
         request.session['cart_id'] = cart_id
         cart = Cart.objects.get(id=cart_id)
      turkey = Country.objects.get(id=1)
      spain = Country.objects.get(id=2)
      country = get_object_or_404(Country, slug__iexact=slug)
      r = requests.get(f'http://localhost:8000/api/shop/country/{country.slug}')
      pprint.pprint(r.json())
      return render(request, 'TourfirmApp/country_detail.html', context={
         'country': r.json(),
         'turkey': turkey,
         'spain': spain,
         'cart':cart,
      })


class ToursList(View):
   def get(self, request):
      try: 
         cart_id = request.session['cart_id']
         cart = Cart.objects.get(id=cart_id)
         request.session['total'] = cart.items.count()
      except:
         cart = Cart()
         cart.save()
         cart_id = cart.id
         request.session['cart_id'] = cart_id
         cart = Cart.objects.get(id=cart_id)
      r = requests.get('http://localhost:8000/api/shop/country/')
      return render(request, 'TourfirmApp/tours_list.html', context={'countries':r.json(), 'cart': cart,})


def cart_view(request):
   try: 
      cart_id = request.session['cart_id']
      cart = Cart.objects.get(id=cart_id)
      request.session['total'] = cart.items.count()
   except:
      cart = Cart()
      cart.save()
      cart_id = cart.id
      request.session['cart_id'] = cart_id
      cart = Cart.objects.get(id=cart_id)
   context = {
      'cart': cart,
   }
   return render(request, 'TourfirmApp/cart.html', context)


def add_to_cart_view(request):
   try: 
      cart_id = request.session['cart_id']
      cart = Cart.objects.get(id=cart_id)
      request.session['total'] = cart.items.count()
   except:
      cart = Cart()
      cart.save()
      cart_id = cart.id
      request.session['cart_id'] = cart_id
      cart = Cart.objects.get(id=cart_id)
   slug = request.GET.get('country_slug')
   cart.add_to_cart(slug)
   new_cart_total = 0.00
   for item in cart.items.all():
      new_cart_total += float(item.item_total)
   cart.cart_total = new_cart_total
   cart.save()
   return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})
   

def remove_from_cart_view(request):
   try: 
      cart_id = request.session['cart_id']
      cart = Cart.objects.get(id=cart_id)
      request.session['total'] = cart.items.count()
   except:
      cart = Cart()
      cart.save()
      cart_id = cart.id
      request.session['cart_id'] = cart_id
      cart = Cart.objects.get(id=cart_id)
   slug = request.GET.get('country_slug')
   cart.remove_from_cart(slug)
   new_cart_total = 0.00
   for item in cart.items.all():
      new_cart_total += float(item.item_total)
   cart.cart_total = new_cart_total
   cart.save()
   return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def change_item_qty(request):
   try: 
      cart_id = request.session['cart_id']
      cart = Cart.objects.get(id=cart_id)
      request.session['total'] = cart.items.count()
   except:
      cart = Cart()
      cart.save()
      cart_id = cart.id
      request.session['cart_id'] = cart_id
      cart = Cart.objects.get(id=cart_id)
   qty = request.GET.get('qty')
   item_id = request.GET.get('item_id')
   cart_item = CartItem.objects.get(id=int(item_id))
   cart.change_qty(cart_item, qty)
   return JsonResponse({
      'cart_total':cart.items.count(), 
      'item_total':cart_item.item_total,
      'cart_total_price': cart.cart_total,
   })


def checkout_view(request):
   try: 
      cart_id = request.session['cart_id']
      cart = Cart.objects.get(id=cart_id)
      request.session['total'] = cart.items.count()
   except:
      cart = Cart()
      cart.save()
      cart_id = cart.id
      request.session['cart_id'] = cart_id
      cart = Cart.objects.get(id=cart_id)
   context = {
      'cart':cart
   }

   return render(request, 'TourfirmApp/checkout.html', context)


def order_create_view(request):
   try: 
      cart_id = request.session['cart_id']
      cart = Cart.objects.get(id=cart_id)
      request.session['total'] = cart.items.count()
   except:
      cart = Cart()
      cart.save()
      cart_id = cart.id
      request.session['cart_id'] = cart_id
      cart = Cart.objects.get(id=cart_id)
   form = OrderForm()
   if request.method == 'POST':
      form = OrderForm(request.POST)
      if form.is_valid():
         data = {
            'items' : cart,
            'first_name' : form.cleaned_data['name'],
            'last_name' : form.cleaned_data['last_name'],
            'phone' : form.cleaned_data['phone'],
            'address' : form.cleaned_data['address'],
            'buying_type' : form.cleaned_data['buying_type'],
            'comment' : form.cleaned_data['comment'],
            'total' : cart.cart_total
         }
         print(data['buying_type'])
         r = requests.post('http://localhost:8000/api/shop/order/create/', data)
         print(r)
         print(r.json())
         del request.session['cart_id']
         del request.session['total']
         messages.success(request, f'Тапсырыс сәтті қабылданды! Қоңырауды күтіңіз')
         return render(request, 'TourfirmApp/order.html')
   context = {
      'form': form,
      'cart': cart,
   }
   return render(request, 'TourfirmApp/order.html', context)

TourfirmApp/templates/TourfirmApp/cart.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'css/tour.css' %}">
{% endblock links %}
{% block title %}Корзина{% endblock %}


{% block content %}
   <div class="tour-header tour-banner-head">
		<div class="wrapper">
			<div class="tour-nav flex-justify"">
				<div class=" logo logo-tour">
					<a class="topLink" href="{% url 'home_url' %}">Sholpan</a>
				</div>

				<button class="menu-toggle">
					<span></span>
					<span></span>
					<span></span>
				</button>

				<ul class="menu tour-menu">
					<li>
						<a class="topLink" href="{% url 'home_url' %}">Басты бет</a>
					</li>
					<li>
						<a class="topLink" href="{% url 'tours_list_url' %}">Турлар</a>
					</li>
					<li>
						<a class="topLink" href="{% url 'home_url' %}">Галерея</a>
					</li>
					<li>
						<a class="topLink" href="{% url 'home_url' %}">Мәлімет</a>
					</li>
					<li>
						<a class="topLink" href="#footer">Бізбен байланысу</a>
					</li>
				</ul>
			</div>
		</div>
   </div>


   <div class="wrapper">
      {% if cart.items.count > 0 %}
         <div class="my-cart">
            <table cellpadding="12" border="1" cellspacing="0">
               <tr>
                  <td>Тауар</td>
                  <td>Саны</td>
                  <td>Бағасы</td>
                  <td>Әрекет</td>
               </tr>
               {% for item in cart.items.all %}
                  <tr class="cart-item-{{ item.country.id }}">
                     <td>{{ item.country.name }}</td>
                     <td>
                        <form action="" method="GET">
                           <input type="number" name="qty" class="cart-item-qty" data-id="{{ item.id }}" value="{{ item.qty }}" min="1" style="width: 50px;">
                        </form>
                     </td>
                     <td id="cart-item-total-{{ item.id }}">{{ item.item_total }} тенге</td>
                     <td class="remove-td">
                        <a href="#" class="remove_from_cart" data-slug="{{ item.country.slug }}" data-id="{{ item.country.id }}">
                           Себеттен жою
                        </a>
                     </td>
                  </tr>
               {% endfor %}
               <tr>
                  <td><strong>Барлығы:</strong></td>
                  <td></td>
                  <td id="cart-total-price"><strong>{{ cart.cart_total }} тенге</strong></td>
                  <td></td>
               </tr>
            </table>
            <br>
            <p class="order-container">
               <a href="{% url 'checkout_url' %}" class="btn">Алдын-ала тапсырыс</a>
            </p>
         </div>
      {% else %}
         <div class="my-cart empty-tours">
            <h4>Сіздің себетіңіз бос</h4>
            <p>
               <a href="{% url 'tours_list_url' %}">Турлар тізімін көру</a>
            </p>
         </div>
      {% endif %}
      <!-- <h3 class="cart-empty"></h3> -->
   </div>


   <footer id="footer">
      <div class="wrapper">
         <div class="footer-desc">
            <div class="footer-desc__item">
               <div class="footer-logo">
                  <a href="{% url 'home_url' %}">Sholpan</a>
               </div>

               <p class="text__desc">
                  2010 жылдан бастап клиенттерімізді бақытты
                  қылып, жоғары сапада қызмет етудеміз, әр
                  энергиямызды клиентімізге қуанышта арнаудамыз
               </p>
            </div>

            <div class="footer-desc__item">
               <h4>Байланыс ақпараты</h4>

               <ul class="contact-list">
                  <li class="text__desc">
                     <span>
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                     </span>
                     Қайым Мухамедханов көшесі, 14
                  </li>
                  <li class="text__desc">
                     <span>
                        <i class="fa fa-phone" aria-hidden="true"></i>
                     </span>
                     +7 778 787 7878
                  </li>
                  <li class="text__desc">
                     <span>
                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                     </span>
                     info@gmail.com
                  </li>
               </ul>
            </div>

            <div class="footer-desc__item">
               <h4>Әлеуметтік желілерге қосылыңыз</h4>

               <ul class="follow-list">
                  <li>
                     <a class="text__desc" href="#">
                        <i class="fa fa-vk" aria-hidden="true"></i>
                     </a>
                     <a class="text__desc" href="#">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                     </a>
                     <a class="text__desc" href="#">
                        <i class="fa fa-facebook" aria-hidden="true"></i>
                     </a>
                     <a class="text__desc" href="#">
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                     </a>
                  </li>
               </ul>
            </div>
         </div>
      </div>
   </footer>
   <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
   <script>
      $(document).ready(function(){
         $('.remove_from_cart').on('click', function(e){
            e.preventDefault()
            country_slug = $(this).attr('data-slug')
            item_country_id = $(this).attr('data-id')
            data = {
               country_slug: country_slug
            }
            $.ajax({
               type: "GET",
               url: '{% url "remove_from_cart_url" %}',
               data: data,
               success: function(data){
                  $("#cart_count").html(data.cart_total)
                  $('.cart-item-'+item_country_id).css('display', 'none')
                  $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' тенге' + '</strong>')
                  if(parseInt(data.cart_total) == 0 ){
                     $('.my-cart').css('display', 'none')
                     $('.cart-empty').html('<h3>Ваша корзина пуста</h3>')
                  }
               }
            })
         })
      })

      $(document).ready(function(){
         $('.cart-item-qty').on('click', function(){
            qty = $(this).val()
            item_id = $(this).attr('data-id')
            data = {
               qty: qty,
               item_id: item_id
            }
            $.ajax({
               type: "GET",
               url: '{% url "change_item_qty_url" %}',
               data: data,
               success: function(data){
                  $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + ' тенге')
                  $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' тенге' + '</strong>')
               }
            })
         })
      })
   </script>
{% endblock content %}

TourfirmApp/templates/TourfirmApp/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block links %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/tour.css' %}">
{% endblock links %}
{% block title %}Предварительный заказ{% endblock %}


{% block content %}
   <div class="tour-header tour-banner-head">
      <div class="wrapper">
         <div class="tour-nav flex-justify"">
            <div class=" logo logo-tour">
               <a class="topLink" href="{% url 'home_url' %}">Sholpan</a>
            </div>

            <button class="menu-toggle">
               <span></span>
               <span></span>
               <span></span>
            </button>

            <ul class="menu tour-menu">
               <li>
                  <a class="topLink" href="{% url 'home_url' %}">Басты бет</a>
               </li>
               <li>
                  <a class="topLink" href="{% url 'tours_list_url' %}">Турлар</a>
               </li>
               <li>
                  <a class="topLink" href="{% url 'home_url' %}">Галерея</a>
               </li>
               <li>
                  <a class="topLink" href="{% url 'home_url' %}">Мәлімет</a>
               </li>
               <li>
                  <a class="topLink" href="#footer">Бізбен байланысу</a>
               </li>
            </ul>
         </div>
      </div>
   </div>
   <div class="order-box">
      {% if messages %}
         {% for mess in messages %}
            <div class="alert alert-success order-message order-container">
               {{ mess }}
            </div>
         {% endfor %}
      {% endif %}
      <div class="wrapper">
         {% if cart.cart_total == 0 %}
            <div class="order-container order-message">
               <h3 style="color:red;">Сіздің себетіңіз бос</h4>
               <p><a href="{% url 'cart_url' %}">Себет</a></p>
            </div>
         {% else %}
            <form action="" method="POST">
               {% csrf_token %}
               {{ form|crispy }}
               <div class="order-container">
                  <input type="submit" value="Тапсырыс">
               </div>
            </form>
         {% endif %}
      </div>
   </div>

   <footer id="footer">
      <div class="wrapper">
         <div class="footer-desc">
            <div class="footer-desc__item">
               <div class="footer-logo">
                  <a href="{% url 'home_url' %}">Sholpan</a>
               </div>

               <p class="text__desc">
                  2010 жылдан бастап клиенттерімізді бақытты
                  қылып, жоғары сапада қызмет етудеміз, әр
                  энергиямызды клиентімізге қуанышта арнаудамыз
               </p>
            </div>

            <div class="footer-desc__item">
               <h4>Байланыс ақпараты</h4>

               <ul class="contact-list">
                  <li class="text__desc">
                     <span>
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                     </span>
                     Қайым Мухамедханов көшесі, 14
                  </li>
                  <li class="text__desc">
                     <span>
                        <i class="fa fa-phone" aria-hidden="true"></i>
                     </span>
                     +7 778 787 7878
                  </li>
                  <li class="text__desc">
                     <span>
                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                     </span>
                     info@gmail.com
                  </li>
               </ul>
            </div>

            <div class="footer-desc__item">
               <h4>Әлеуметтік желілерге қосылыңыз</h4>

               <ul class="follow-list">
                  <li>
                     <a class="text__desc" href="#">
                        <i class="fa fa-vk" aria-hidden="true"></i>
                     </a>
                     <a class="text__desc" href="#">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                     </a>
                     <a class="text__desc" href="#">
                        <i class="fa fa-facebook" aria-hidden="true"></i>
                     </a>
                     <a class="text__desc" href="#">
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                     </a>
                  </li>
               </ul>
            </div>
         </div>
      </div>
   </footer>

   <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
   <script>
      $(document).ready(function(){
         $('#div_id_address').css('display', 'none')
         $('#id_buying_type').on('click', function(){
            buying_type = $(this).val()
            if(buying_type == 'delivery'){
               $('#div_id_address').css('display', 'block')
            }else{
               $('#div_id_address').css('display', 'none')
            }
         })
         $('#id_date_month').css('width', '110px')
         $('#id_date_year').css('width', '110px')
         $('#id_date_day').css('width', '110px')
         $('#id_date_month').css('display', 'inline')
         $('#id_date_year').css('display', 'inline')
         $('#id_date_day').css('display', 'inline')
      })
   </script>
{% endblock %}